---
# This works by first comparing the current version to the version specified in global_vars/all file
- name: Set JAVA_HOME fact
  set_fact:
    java_home: "{{ java_oracle_jdk_install_path }}"

- name: Check Java version
  command: java -version
  register: java_check_version
  changed_when: false
  ignore_errors: true

- name: Download .tar.gz file containing binaries from Oracle website
  get_url:
    url: "{{ java_oracle_jdk_latest_versions_urls[java_oracle_jdk_version].url }}"
    dest: "/tmp/jdk-{{ java_oracle_jdk_version }}.tar.gz"
    # That implies that you accept the Oracle Binary Code License Agreement for Java SE (http://www.oracle.com/technetwork/java/javase/terms/license/index.html)
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    sha256sum: "{{ java_oracle_jdk_latest_versions_urls[java_oracle_jdk_version].sha256 }}"
  when: java_check_version is failed or java_oracle_jdk_version not in java_check_version.stderr
  register: download_java_binaries

- name: Ensure installation dir exists
  file:
    state: directory
    path: "{{ java_oracle_jdk_install_path }}"

- name: Extract java in the installation directory
  unarchive:
    copy: no
    src: "/tmp/jdk-{{ java_oracle_jdk_version }}.tar.gz"
    dest: "{{ java_oracle_jdk_install_path }}"
    extra_opts: [--strip-components=1]
  when: java_check_version is failed or java_oracle_jdk_version not in java_check_version.stderr

- name: Java | Export environment variables
  template:
    src: custom.sh.j2
    dest: /etc/profile.d/custom.sh
    mode: 0644
  when: download_java_binaries is changed

- name: Java | Update alternatives
  alternatives:
    name: "{{ item }}"
    link: /usr/bin/{{ item }}
    path: "{{ java_oracle_jdk_install_path }}/bin/{{ item }}"
  with_items:
    - "java"
    - "javac"
    - "jar"
  when: download_java_binaries is changed